// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.
export type EngineId =
  | "canvas"
  | "exif"
  | "heic"
  | "jsquash-avif"
  | "jsquash-jpeg"
  | "jsquash-jxl"
  | "jsquash-png"
  | "jsquash-resize"
  | "jsquash-webp"
  | "libraw"
  | "pdf-lib"
  | "psd"
  | "resvg"
  | "tracer"
  | "utif";
