// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.
/**
 * WORKER-ONLY. Only a worker may import this module — importing it from
 * main-thread code would pull every engine adapter into the core bundle
 * (see docs/ARCHITECTURE.md, "Engines"); `check-sizes` would catch it.
 */

import type { EngineId } from "./ids";
import type { EngineAdapter } from "./types";

export const ENGINE_LOADERS = {
  canvas: () => import("./canvas/adapter"),
  exif: () => import("./exif/adapter"),
  heic: () => import("./heic/adapter"),
  "jsquash-avif": () => import("./jsquash-avif/adapter"),
  "jsquash-jpeg": () => import("./jsquash-jpeg/adapter"),
  "jsquash-jxl": () => import("./jsquash-jxl/adapter"),
  "jsquash-png": () => import("./jsquash-png/adapter"),
  "jsquash-resize": () => import("./jsquash-resize/adapter"),
  "jsquash-webp": () => import("./jsquash-webp/adapter"),
  libraw: () => import("./libraw/adapter"),
  "pdf-lib": () => import("./pdf-lib/adapter"),
  pdfjs: () => import("./pdfjs/adapter"),
  psd: () => import("./psd/adapter"),
  resvg: () => import("./resvg/adapter"),
  tracer: () => import("./tracer/adapter"),
  utif: () => import("./utif/adapter"),
} satisfies Record<EngineId, () => Promise<{ default: EngineAdapter }>>;
