// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.
/**
 * WORKER-ONLY. Only a worker may import this module — importing it from
 * main-thread code would pull every engine adapter into the core bundle
 * (see docs/ARCHITECTURE.md, "Engines"); `check-sizes` would catch it.
 */

import type { EngineId } from "./ids";
import type { EngineAdapter } from "./types";

export const ENGINE_LOADERS = {
  canvas: () => import("./canvas/adapter"),
  exif: () => import("./exif/adapter"),
} satisfies Record<EngineId, () => Promise<{ default: EngineAdapter }>>;
