// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.
import type { EngineManifestEntry } from "./meta";

export const ENGINE_MANIFEST = {
  canvas: {
    id: "canvas",
    version: "1.0.0",
    license: "MIT",
    location: "native",
    needsIsolation: false,
    heavy: false,
    assets: [],
    baseUrl: "",
    totalBytes: 0,
  },
} as const satisfies Record<string, EngineManifestEntry>;
