// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.
import type { EngineManifestEntry } from "./meta";

export const ENGINE_MANIFEST = {} as const satisfies Record<
  string,
  EngineManifestEntry
>;
