import { readFileSync } from "node:fs";
import { test as base, expect } from "@playwright/test";

/**
 * First live end-to-end run of the libreoffice engine (ADR-0012):
 * `location: "r2"`, ~74 MB gzipped, consent-gated — same shape as
 * `e2e/legacy-video.spec.ts`'s ffmpeg, just a much bigger download and a
 * much slower init (real LibreOfficeKit boot, not a single-purpose codec).
 *
 * `e2e/fixtures/sample.docx` is a minimal, hand-built WordprocessingML
 * document generated by `scripts/gen-office-fixture.ts` (committed alongside
 * this spec) — no Word/LibreOffice involved in producing the fixture itself,
 * just enough OOXML for LibreOffice to import: one paragraph, "Hello
 * Localvert".
 */
function fixturePath(name: string): string {
  return `e2e/fixtures/${name}`;
}

function hasPdfMagic(bytes: Uint8Array): boolean {
  return Buffer.from(bytes).subarray(0, 5).toString("latin1") === "%PDF-";
}

/** Same `pdfjs-dist` (legacy/Node build) text extraction as
 * `e2e/pdf-editor-redact.spec.ts`'s `extractText`. */
async function extractText(bytes: Buffer): Promise<string> {
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const doc = await pdfjs.getDocument({ data: new Uint8Array(bytes) }).promise;
  let text = "";
  for (let i = 1; i <= doc.numPages; i++) {
    const page = await doc.getPage(i);
    const content = await page.getTextContent();
    for (const item of content.items) {
      if ("str" in item) text += `${item.str} `;
    }
  }
  return text;
}

interface Fixtures {
  /** Autouse: fails the test if any request left the page's own origin. */
  privacyGuard: undefined;
  /** Autouse: fails the test if the browser ever reported a CSP violation. */
  cspGuard: undefined;
}

const test = base.extend<Fixtures>({
  privacyGuard: [
    async ({ page, baseURL }, use) => {
      const ownOrigin = new URL(baseURL ?? "http://localhost:8788").origin;
      const foreign: string[] = [];
      page.on("request", (request) => {
        const origin = new URL(request.url()).origin;
        if (origin !== ownOrigin) foreign.push(request.url());
      });

      await use(undefined);

      expect(
        foreign,
        "no request should ever leave the page's own origin — files never leave the browser",
      ).toEqual([]);

      const isolated = await page.evaluate(() => self.crossOriginIsolated);
      expect(
        isolated,
        "page must be cross-origin isolated (COOP/COEP from public/_headers)",
      ).toBe(true);
    },
    { auto: true },
  ],

  cspGuard: [
    async ({ page }, use) => {
      const violations: string[] = [];
      await page.exposeFunction("__onCspViolation", (detail: string) => {
        violations.push(detail);
      });
      await page.addInitScript(() => {
        document.addEventListener("securitypolicyviolation", (e) => {
          // @ts-expect-error — bridged in by exposeFunction above.
          window.__onCspViolation(`${e.violatedDirective}: ${e.blockedURI}`);
        });
      });

      await use(undefined);

      expect(violations, "no CSP violation should occur").toEqual([]);
    },
    { auto: true },
  ],
});

test.describe("word to pdf (libreoffice engine, ADR-0012)", () => {
  test("gates the libreoffice download behind consent, then converts a real docx", async ({
    page,
  }) => {
    // Real ~74 MB gzipped fetch + a real LibreOfficeKit boot + a real
    // conversion — the slowest engine this app ships. Generous but bounded,
    // per the brief's 180s budget for the conversion step itself.
    test.setTimeout(300_000);
    const engineRequests: { url: string; status: number }[] = [];
    page.on("response", (response) => {
      if (response.url().includes("/engines/xl/libreoffice@")) {
        engineRequests.push({ url: response.url(), status: response.status() });
      }
    });

    await page.goto("/tools/word-to-pdf");

    await page
      .locator('input[type="file"]')
      .setInputFiles(fixturePath("sample.docx"));

    const dialog = page.getByRole("dialog", {
      name: "Download the libreoffice engine?",
    });
    await expect(dialog).toBeVisible();

    await dialog.getByRole("button", { name: "Download and convert" }).click();
    await expect(dialog).toBeHidden();

    const downloadLink = page.getByRole("link", { name: "Download" });
    await expect(downloadLink).toBeVisible({ timeout: 180_000 });

    expect(
      engineRequests.length,
      "the libreoffice engine must be fetched from this origin's /engines/xl/ prefix",
    ).toBeGreaterThan(0);
    for (const req of engineRequests) {
      expect([200, 206], `${req.url} should succeed`).toContain(req.status);
    }

    const downloadPromise = page.waitForEvent("download");
    await downloadLink.click();
    const download = await downloadPromise;
    const path = await download.path();
    if (!path) throw new Error("download produced no local path");

    const bytes = readFileSync(path);
    expect(hasPdfMagic(bytes)).toBe(true);

    const text = await extractText(bytes);
    expect(text).toContain("Hello Localvert");
  });
});
