import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { pathToFileURL } from "node:url";

/**
 * Post-build step: bundles src/sw.ts into out/sw.js and injects its
 * precache manifest — the {url, revision} entries the service worker
 * fetches and caches on install.
 *
 * ORDERING TRAP — read before touching this file or package.json's `build`
 * script. `pnpm build` runs three steps in sequence:
 *
 *   1. `next build`                     produces `out/`
 *   2. `scripts/csp-inline-hashes.ts`   rewrites every out/**\/*.html,
 *      injecting a per-page <meta> CSP (docs/adr/0006)
 *   3. `scripts/build-sw.ts` (this file)
 *
 * @serwist/turbopack's usual integration — a Next.js Route Handler,
 * generated by `createSerwistRoute` and wired up with `withSerwist` in
 * next.config.ts, conventionally at `app/serwist/[path]/route.ts` — builds
 * its precache manifest by globbing `.next/` DURING `next build`'s own
 * static-generation phase. That's step 1, before step 2 has touched a
 * single byte, and before `out/` even exists at all (`next build` writes
 * `out/` as its own last act). A manifest built that early would embed HTML
 * revisions hashed from the pre-injection bytes — they'd stop matching the
 * instant step 2 rewrites every page's <head>, so a browser would precache
 * a page revision that never matches what's actually served, and Serwist
 * would never know to re-fetch it on a later, genuinely different build.
 *
 * So this script does not use that Route Handler, and there is no
 * `app/serwist/[path]/route.ts` in this project. It imports
 * `createSerwistRoute` from `@serwist/turbopack` directly — the same
 * function the Route Handler wraps — and drives it itself, as a plain Node
 * script, after steps 1 and 2 have both already run, pointed at the real
 * `out/` directory instead of `.next/`. Every byte this script hashes is
 * already final; nothing downstream can invalidate it.
 *
 * `findMissingCspMarker` (used in `main`) is a cheap, mechanical guard
 * against exactly the mistake this comment describes: if `pnpm build`'s
 * steps were ever reordered so this script ran before csp-inline-hashes.ts,
 * every out/**\/*.html would be missing its injected <meta> marker, and
 * this script fails loudly (exit 1) instead of silently baking in stale
 * revisions.
 *
 * Runs as plain `node scripts/build-sw.ts` — Node's built-in TypeScript
 * type stripping, same as the other scripts here. Keep it to erasable
 * syntax only: no enums, no namespaces, no parameter properties. No imports
 * of our own modules — see the header comment in scripts/gen-registry.ts
 * for why; the one constant shared with csp-inline-hashes.ts
 * (`CSP_META_MARKER`) is duplicated rather than imported.
 */

const OUT_DIR = "out";

// Must match `META_MARKER` in scripts/csp-inline-hashes.ts exactly.
const CSP_META_MARKER = "data-localvert-csp";

function walkHtmlFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkHtmlFiles(full));
    } else if (entry.isFile() && entry.name.endsWith(".html")) {
      files.push(full);
    }
  }
  return files;
}

/**
 * Pure: which of these (path, html) pairs is missing the CSP <meta> tag
 * csp-inline-hashes.ts injects. An empty result means it's safe to compute
 * precache revisions from this content — see the module doc comment above.
 */
export function findMissingCspMarker(
  files: readonly { path: string; html: string }[],
): string[] {
  return files
    .filter((f) => !f.html.includes(CSP_META_MARKER))
    .map((f) => f.path);
}

/** sha256 of `content`, hex-encoded — the precache revision for an HTML page. */
export function sha256Hex(content: Buffer | string): string {
  return createHash("sha256").update(content).digest("hex");
}

/**
 * The pretty URL a browser actually requests for a given out/-relative HTML
 * file path, matching how Cloudflare's asset handling
 * (`html_handling: "auto-trailing-slash"` in infra/wrangler.jsonc) resolves
 * a clean URL to its .html file: "index.html" -> "/", "foo/index.html" ->
 * "/foo", "foo.html" -> "/foo". Mirrors `pageLabel` in
 * scripts/check-sizes.ts (duplicated rather than imported — see the module
 * doc comment above).
 */
export function prettyUrlFor(outRelativeHtmlPath: string): string {
  const posixPath = outRelativeHtmlPath.split("\\").join("/");
  if (posixPath === "index.html") return "/";
  if (posixPath.endsWith("/index.html")) {
    return `/${posixPath.slice(0, -"/index.html".length)}`;
  }
  return `/${posixPath.slice(0, -".html".length)}`;
}

async function main() {
  const outDir = join(process.cwd(), OUT_DIR);
  if (!existsSync(outDir)) {
    console.error(
      `build-sw: "${OUT_DIR}/" does not exist — run \`next build\` first.`,
    );
    process.exit(1);
  }

  const htmlFiles = walkHtmlFiles(outDir).map((file) => ({
    path: relative(outDir, file),
    html: readFileSync(file, "utf8"),
  }));
  const missing = findMissingCspMarker(htmlFiles);
  if (missing.length > 0) {
    console.error(
      `build-sw: ${missing.length} page(s) in out/ are missing their injected CSP <meta> tag — ` +
        "scripts/csp-inline-hashes.ts must run before scripts/build-sw.ts (see package.json's " +
        `"build" script). Affected: ${missing.slice(0, 5).join(", ")}${missing.length > 5 ? ", …" : ""}`,
    );
    process.exit(1);
  }

  // Force production semantics (minified output, manifest actually
  // generated — @serwist/turbopack disables precaching entirely in dev)
  // regardless of the calling shell's own environment. Must happen before
  // the dynamic import below: @serwist/turbopack reads process.env.NODE_ENV
  // once, at module load time, and a static top-level `import` would be
  // hoisted ahead of this assignment.
  if (process.env.NODE_ENV !== "production") {
    // `NODE_ENV` is typed read-only (Next augments its type); Object.assign
    // writes the same underlying process.env without fighting that type.
    Object.assign(process.env, { NODE_ENV: "production" });
  }
  const { createSerwistRoute } = await import("@serwist/turbopack");

  const route = createSerwistRoute({
    swSrc: "src/sw.ts",
    globDirectory: outDir,
    globPatterns: ["**/*.html", "_next/static/**/*.{js,css}"],
    globIgnores: [
      "**/node_modules/**/*",
      // Runtime-cached by src/sw.ts's own CacheFirst rule, not precached.
      "engines/**",
    ],
    // _next/static filenames are already content-hashed by `next build`;
    // don't also append a ?__WB_REVISION__= cache-busting param to them.
    dontCacheBustURLsMatching: /^_next\/static\//,
    // Avoid depending on esbuild-wasm, which isn't a resolved dependency —
    // only `esbuild` (native) is, via @serwist/turbopack's own peer deps.
    useNativeEsbuild: true,
    manifestTransforms: [
      async (entries) => ({
        manifest: entries.map((entry) => {
          if (!entry.url.endsWith(".html")) {
            // "_next/static/chunks/foo.js" -> "/_next/static/chunks/foo.js"
            return { ...entry, url: `/${entry.url}` };
          }
          // Revision from the file's current bytes — already final, this
          // script only ever runs after csp-inline-hashes.ts (enforced
          // above).
          const revision = sha256Hex(readFileSync(join(outDir, entry.url)));
          return { ...entry, url: prettyUrlFor(entry.url), revision };
        }),
        warnings: [],
      }),
    ],
  });

  const params = await route.generateStaticParams();
  for (const { path } of params) {
    const response = await route.GET(new Request("http://localhost/sw.js"), {
      params: Promise.resolve({ path }),
    });
    writeFileSync(join(outDir, path), await response.text());
  }

  process.stdout.write(`build-sw: wrote ${params.length} file(s) to out/.\n`);
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  await main();
}
