/**
 * `pnpm gen` — regenerates the tool barrel (`src/tools/index.ts`), the
 * per-tool code-splitting map (`src/tools/loaders.ts`), and the engine
 * ids/manifest/loaders (`src/lib/engines/{ids,manifest,loaders}.ts`) by
 * statically scanning `src/tools/<category>/*.ts` and
 * `src/lib/engines/<id>/{engine.json,adapter.ts}`.
 *
 * Static source scanning only — this script never imports or executes a
 * tool or adapter file (see docs/ARCHITECTURE.md, "The registry: tools are
 * data, not code"). It only reads file *paths* under `src/tools/` and the
 * JSON *text* of each engine's `engine.json`; nothing under `src/` is
 * `import`ed, so a broken tool/adapter file can never break generation.
 * For the same reason this script is fully self-contained — no imports of
 * our own modules, not even by relative path — mirroring
 * `scripts/check-sizes.ts` and `scripts/csp-inline-hashes.ts`: those run
 * outside any tsconfig program (Node's own module resolution has no idea
 * about the "@/" path alias), so anything they need is duplicated locally
 * rather than imported.
 *
 * Generated files are checked in; CI fails if `pnpm gen` produces a diff.
 *
 * Runs as plain `node scripts/gen-registry.ts` (Node's built-in TypeScript
 * type stripping — no build step for this script itself). Keep it to
 * erasable syntax only: no enums, no namespaces, no parameter properties.
 */
import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";

const GENERATED_HEADER =
  "// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.";

// ---------------------------------------------------------------------------
// Tools: src/tools/<category>/*.ts -> src/tools/index.ts
// ---------------------------------------------------------------------------

export interface ToolFileInfo {
  /** Directory name under src/tools/, e.g. "image". */
  category: string;
  /** Filename without extension, e.g. "jpg-to-png". */
  slug: string;
  /** Import specifier the generated barrel uses. */
  importPath: string;
  /** Generated identifier for the tool's default import. */
  varName: string;
}

/** kebab-case -> camelCase, for a generated default-import identifier. */
function toCamelCase(kebab: string): string {
  const camel = kebab.replace(/-([a-z0-9])/g, (_, c: string) =>
    c.toUpperCase(),
  );
  // A slug may start with a digit (see SLUG_RE in define-tool.ts); that
  // would make the camelCased result an invalid identifier on its own.
  return /^[0-9]/.test(camel) ? `_${camel}` : camel;
}

/**
 * Scans `src/tools/<category>/*.ts`, skipping `*.test.ts` and `index.ts`.
 * Returns an empty list if `src/tools/` doesn't exist yet — a fresh repo
 * with zero tools is a valid state (see `genToolsIndex`).
 *
 * Only paths are read here, never file contents — see the module doc
 * comment, "Static source scanning only".
 */
export function scanTools(rootDir: string): ToolFileInfo[] {
  const toolsDir = join(rootDir, "src", "tools");
  if (!existsSync(toolsDir)) return [];

  const categories = readdirSync(toolsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const infos: ToolFileInfo[] = [];
  const usedNames = new Set<string>();

  for (const category of categories) {
    const files = readdirSync(join(toolsDir, category), {
      withFileTypes: true,
    })
      .filter((d) => d.isFile() && d.name.endsWith(".ts"))
      .map((d) => d.name)
      .filter((name) => name !== "index.ts" && !name.endsWith(".test.ts"))
      .sort();

    for (const file of files) {
      const slug = file.slice(0, -".ts".length);
      const shortName = toCamelCase(slug);
      // Disambiguate a name collision across categories deterministically:
      // the first occurrence (sorted by category, then filename) keeps the
      // short name; a later collision gets the category folded in.
      const varName = usedNames.has(shortName)
        ? toCamelCase(`${category}-${slug}`)
        : shortName;
      usedNames.add(varName);
      infos.push({
        category,
        slug,
        importPath: `@/tools/${category}/${slug}`,
        varName,
      });
    }
  }

  return infos;
}

export function genToolsIndex(tools: readonly ToolFileInfo[]): string {
  const imports = tools.map(
    (t) => `import ${t.varName} from "${t.importPath}";`,
  );
  const list = tools.map((t) => t.varName).join(", ");

  return `${[
    GENERATED_HEADER,
    `import type { ToolDefinition } from "@/lib/registry";`,
    ...imports,
    "",
    `export const TOOLS: readonly ToolDefinition[] = [${list}];`,
    "",
    "export const TOOLS_BY_SLUG: ReadonlyMap<string, ToolDefinition> = new Map(",
    "  TOOLS.map((t) => [t.slug, t]),",
    ");",
  ].join("\n")}\n`;
}

/**
 * Per-tool code splitting: a client page loads exactly one tool's module via
 * this map instead of importing the `TOOLS` barrel (which pulls in every
 * tool's pipeline and, transitively, its option schema — see
 * docs/ADDING_A_TOOL.md). Keyed by slug, which by convention **is** the
 * tool's file basename (`scanTools`'s `t.slug`) — `src/tools/registry.test.ts`
 * enforces that every tool's declared `slug` actually matches its filename,
 * which is what makes this map's keys trustworthy without importing the tool
 * modules here to check.
 */
export function genToolsLoaders(tools: readonly ToolFileInfo[]): string {
  const entries = tools.map(
    (t) => `  "${t.slug}": () => import("./${t.category}/${t.slug}"),`,
  );
  const body = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;

  return `${[
    GENERATED_HEADER,
    `import type { ToolDefinition } from "@/lib/registry";`,
    "",
    `export const TOOL_LOADERS = ${body} satisfies Record<`,
    "  string,",
    "  () => Promise<{ default: ToolDefinition }>",
    ">;",
  ].join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Engines: src/lib/engines/<id>/{engine.json,adapter.ts} -> ids.ts / manifest.ts / loaders.ts
// ---------------------------------------------------------------------------

const ENGINE_LOCATIONS = ["native", "static", "r2"] as const;
type EngineLocationLike = (typeof ENGINE_LOCATIONS)[number];

export interface EngineAssetLike {
  path: string;
  bytes: number;
}

/** Mirrors `src/lib/engines/types.ts`'s `EngineSourceFile`. */
export interface EngineSourceFileLike {
  from: string;
  to: string;
}

/** Mirrors `src/lib/engines/meta.ts`'s `EngineMeta` — see that file for the shape this script must produce. */
export interface EngineMetaLike {
  id: string;
  version: string;
  license: string;
  location: EngineLocationLike;
  needsIsolation: boolean;
  heavy: boolean;
  assets: readonly EngineAssetLike[];
  /** Required iff `location` is "static" or "r2"; forbidden for "native" — see `parseEngineMeta`. */
  package?: string;
  files?: readonly EngineSourceFileLike[];
}

const SEMVER_RE = /^\d+\.\d+\.\d+([-+][0-9A-Za-z.-]+)?$/;

/**
 * Parses and validates one engine directory's `engine.json` text against
 * the contract in `src/lib/engines/meta.ts`. Throws a
 * `[gen-registry] engine "<dir>": ...` message on any violation.
 */
export function parseEngineMeta(
  dirName: string,
  rawJson: string,
): EngineMetaLike {
  const fail = (message: string): never => {
    throw new Error(`[gen-registry] engine "${dirName}": ${message}`);
  };

  const parsed: unknown = JSON.parse(rawJson);
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    fail("engine.json must be a JSON object");
  }
  const j = parsed as Record<string, unknown>;

  if (typeof j.id !== "string" || j.id === "") {
    fail(`"id" must be a non-empty string`);
  }
  if (j.id !== dirName) {
    fail(
      `"id" ("${String(j.id)}") must match its directory name ("${dirName}")`,
    );
  }
  if (typeof j.version !== "string" || !SEMVER_RE.test(j.version)) {
    fail(
      `"version" (${JSON.stringify(j.version)}) must be semver, e.g. "1.0.0"`,
    );
  }
  if (typeof j.license !== "string" || j.license.trim() === "") {
    fail(`"license" must be a non-empty string`);
  }
  if (
    typeof j.location !== "string" ||
    !(ENGINE_LOCATIONS as readonly string[]).includes(j.location)
  ) {
    fail(
      `"location" (${JSON.stringify(j.location)}) must be one of ${ENGINE_LOCATIONS.join(", ")}`,
    );
  }
  if (typeof j.needsIsolation !== "boolean") {
    fail(`"needsIsolation" must be a boolean`);
  }
  if (typeof j.heavy !== "boolean") {
    fail(`"heavy" must be a boolean`);
  }
  if (!Array.isArray(j.assets)) {
    fail(`"assets" must be an array`);
  }

  const assets: EngineAssetLike[] = (j.assets as unknown[]).map((a, i) => {
    if (typeof a !== "object" || a === null) {
      fail(`"assets[${i}]" must be an object`);
    }
    const asset = a as Record<string, unknown>;
    if (typeof asset.path !== "string" || asset.path === "") {
      fail(`"assets[${i}].path" must be a non-empty string`);
    }
    if (typeof asset.bytes !== "number" || asset.bytes < 0) {
      fail(`"assets[${i}].bytes" must be a non-negative number`);
    }
    return { path: asset.path as string, bytes: asset.bytes as number };
  });

  // "package"/"files" name the npm package and files `sync-engines` copies
  // the engine's assets from — meaningless for "native", which wraps a
  // browser API and ships nothing of its own.
  const needsSource = j.location === "static" || j.location === "r2";
  let pkg: string | undefined;
  let files: EngineSourceFileLike[] | undefined;

  if (needsSource) {
    if (typeof j.package !== "string" || j.package.trim() === "") {
      fail(`"package" is required when location is "${j.location}"`);
    }
    pkg = j.package as string;

    if (!Array.isArray(j.files) || j.files.length === 0) {
      fail(
        `"files" is required when location is "${j.location}" and must be a non-empty array`,
      );
    }
    files = (j.files as unknown[]).map((f, i) => {
      if (typeof f !== "object" || f === null) {
        fail(`"files[${i}]" must be an object`);
      }
      const file = f as Record<string, unknown>;
      if (typeof file.from !== "string" || file.from === "") {
        fail(`"files[${i}].from" must be a non-empty string`);
      }
      if (typeof file.to !== "string" || file.to === "") {
        fail(`"files[${i}].to" must be a non-empty string`);
      }
      return { from: file.from as string, to: file.to as string };
    });
  } else {
    if (j.package !== undefined) {
      fail(`"package" is not allowed when location is "native"`);
    }
    if (j.files !== undefined) {
      fail(`"files" is not allowed when location is "native"`);
    }
  }

  return {
    id: j.id as string,
    version: j.version as string,
    license: j.license as string,
    location: j.location as EngineLocationLike,
    needsIsolation: j.needsIsolation as boolean,
    heavy: j.heavy as boolean,
    assets,
    ...(pkg !== undefined && files !== undefined
      ? { package: pkg, files }
      : {}),
  };
}

/**
 * Throws if two engines share an `id`. Structurally this can't happen via
 * `scanEngines` alone (a directory's `id` must equal its own, necessarily
 * unique, directory name — see `parseEngineMeta`), but it's cheap defensive
 * validation, and it's exposed separately so it can be exercised directly
 * with hand-built `EngineMetaLike`s, no filesystem required.
 */
export function assertNoDuplicateIds(metas: readonly EngineMetaLike[]): void {
  const seen = new Set<string>();
  for (const meta of metas) {
    if (seen.has(meta.id)) {
      throw new Error(`[gen-registry] duplicate engine id "${meta.id}"`);
    }
    seen.add(meta.id);
  }
}

/**
 * Scans `src/lib/engines/<id>/`. A subdirectory counts as an engine only
 * once it has *both* `engine.json` and `adapter.ts` — one without the other
 * is a broken engine directory and fails generation, since it's plausibly
 * a half-finished `add-engine` in progress rather than something to skip
 * silently. A subdirectory with neither file (unrelated to an engine) is
 * ignored.
 */
export function scanEngines(rootDir: string): EngineMetaLike[] {
  const enginesDir = join(rootDir, "src", "lib", "engines");
  if (!existsSync(enginesDir)) return [];

  const dirNames = readdirSync(enginesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const metas: EngineMetaLike[] = [];

  for (const dirName of dirNames) {
    const dir = join(enginesDir, dirName);
    const hasJson = existsSync(join(dir, "engine.json"));
    const hasAdapter = existsSync(join(dir, "adapter.ts"));

    if (!hasJson && !hasAdapter) continue;

    if (hasJson && !hasAdapter) {
      throw new Error(
        `[gen-registry] engine "${dirName}" has engine.json but no adapter.ts`,
      );
    }
    if (hasAdapter && !hasJson) {
      throw new Error(
        `[gen-registry] engine "${dirName}" has adapter.ts but no engine.json`,
      );
    }

    const rawJson = readFileSync(join(dir, "engine.json"), "utf8");
    metas.push(parseEngineMeta(dirName, rawJson));
  }

  assertNoDuplicateIds(metas);
  return metas;
}

/**
 * Duplicated from `src/lib/engines/meta.ts`'s `engineBaseUrl` rather than
 * imported — see the module doc comment on why this script imports nothing
 * of our own.
 */
function engineBaseUrl(
  id: string,
  version: string,
  location: EngineLocationLike,
): string {
  switch (location) {
    case "native":
      return "";
    case "static":
      return `/engines/${id}@${version}/`;
    case "r2":
      return `/engines/xl/${id}@${version}/`;
  }
}

function sortedById<T extends { id: string }>(metas: readonly T[]): T[] {
  return [...metas].sort((a, b) => a.id.localeCompare(b.id));
}

export function genEngineIds(metas: readonly EngineMetaLike[]): string {
  const ids = metas.map((m) => m.id).sort();
  const union =
    ids.length === 0 ? "never" : ids.map((id) => `"${id}"`).join(" | ");
  return `${GENERATED_HEADER}\nexport type EngineId = ${union};\n`;
}

export function genEngineManifest(metas: readonly EngineMetaLike[]): string {
  const entries = sortedById(metas).map((m) => {
    const totalBytes = m.assets.reduce((sum, a) => sum + a.bytes, 0);
    const baseUrl = engineBaseUrl(m.id, m.version, m.location);
    const assets = m.assets
      .map((a) => `{ path: "${a.path}", bytes: ${a.bytes} }`)
      .join(", ");
    return [
      `  ${m.id}: {`,
      `    id: "${m.id}",`,
      `    version: "${m.version}",`,
      `    license: "${m.license}",`,
      `    location: "${m.location}",`,
      `    needsIsolation: ${m.needsIsolation},`,
      `    heavy: ${m.heavy},`,
      `    assets: [${assets}],`,
      `    baseUrl: "${baseUrl}",`,
      `    totalBytes: ${totalBytes},`,
      "  },",
    ].join("\n");
  });

  const body = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;

  return `${[
    GENERATED_HEADER,
    `import type { EngineManifestEntry } from "./meta";`,
    "",
    `export const ENGINE_MANIFEST = ${body} as const satisfies Record<`,
    "  string,",
    "  EngineManifestEntry",
    ">;",
  ].join("\n")}\n`;
}

export function genEngineLoaders(metas: readonly EngineMetaLike[]): string {
  const entries = sortedById(metas).map(
    (m) => `  ${m.id}: () => import("./${m.id}/adapter"),`,
  );
  const body = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;

  return `${[
    GENERATED_HEADER,
    "/**",
    " * WORKER-ONLY. Only a worker may import this module — importing it from",
    " * main-thread code would pull every engine adapter into the core bundle",
    ' * (see docs/ARCHITECTURE.md, "Engines"); `check-sizes` would catch it.',
    " */",
    `import type { EngineAdapter } from "./types";`,
    `import type { EngineId } from "./ids";`,
    "",
    `export const ENGINE_LOADERS = ${body} satisfies Record<`,
    "  EngineId,",
    "  () => Promise<{ default: EngineAdapter }>",
    ">;",
  ].join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Orchestration
// ---------------------------------------------------------------------------

/**
 * Pure: scans `rootDir` and returns the full set of generated files, keyed
 * by path relative to `rootDir` (forward slashes, regardless of platform).
 * Deterministic — calling this twice against the same `rootDir` produces
 * identical output. `main()` is the only impure part: it writes these to
 * disk and runs Biome over them.
 */
export function generate(rootDir: string): Map<string, string> {
  const tools = scanTools(rootDir);
  const engines = scanEngines(rootDir);

  return new Map([
    ["src/tools/index.ts", genToolsIndex(tools)],
    ["src/tools/loaders.ts", genToolsLoaders(tools)],
    ["src/lib/engines/ids.ts", genEngineIds(engines)],
    ["src/lib/engines/manifest.ts", genEngineManifest(engines)],
    ["src/lib/engines/loaders.ts", genEngineLoaders(engines)],
  ]);
}

function main(): void {
  const rootDir = process.cwd();

  let files: Map<string, string>;
  try {
    files = generate(rootDir);
  } catch (e) {
    console.error(e instanceof Error ? e.message : String(e));
    process.exit(1);
  }

  const writtenPaths: string[] = [];
  for (const [relPath, content] of files) {
    const fullPath = join(rootDir, relPath);
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, content);
    writtenPaths.push(fullPath);
  }

  // Formats and lint-fixes the output in place, so `pnpm gen` alone produces
  // final, `pnpm lint`-clean files — CI runs `pnpm gen` and fails on any
  // diff, so this step can't be a separate manual "remember to lint" step.
  const biomeBin = join(
    rootDir,
    "node_modules",
    "@biomejs",
    "biome",
    "bin",
    "biome",
  );
  execFileSync(
    process.execPath,
    [biomeBin, "check", "--write", ...writtenPaths],
    {
      stdio: "inherit",
    },
  );

  // biome-ignore lint/suspicious/noConsole: pnpm gen's own completion summary.
  console.log(`gen-registry: wrote ${writtenPaths.length} file(s).`);
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main();
}
