/**
 * `pnpm gen` — regenerates the tool barrel (`src/tools/index.ts`), the
 * per-tool code-splitting map (`src/tools/loaders.ts`), the generated tool
 * catalog (`src/tools/catalog.ts`), and the engine
 * ids/manifest/loaders (`src/lib/engines/{ids,manifest,loaders}.ts`) by
 * statically scanning `src/tools/<category>/*.ts` and
 * `src/lib/engines/<id>/{engine.json,adapter.ts}`.
 *
 * Static source scanning only — this script never *imports or executes* a
 * tool or adapter file (see docs/ARCHITECTURE.md, "The registry: tools are
 * data, not code"). Path scanning (`scanTools`) never reads file contents at
 * all; the catalog (`scanToolCatalog`/`parseToolCatalogEntry`) and the engine
 * scan (`scanEngines`) do read a file's *text* — the same way this script
 * reads each engine's `engine.json` as JSON text — but only to pattern-match
 * a handful of plain literal fields, never to `import()` or otherwise run
 * the module. Nothing under `src/` is ever `import`ed, so a broken
 * tool/adapter file can never break generation. For the same reason this
 * script is fully self-contained — no imports of our own modules, not even
 * by relative path — mirroring `scripts/check-sizes.ts` and
 * `scripts/csp-inline-hashes.ts`: those run outside any tsconfig program
 * (Node's own module resolution has no idea about the "@/" path alias), so
 * anything they need is duplicated locally rather than imported.
 *
 * Generated files are checked in; CI fails if `pnpm gen` produces a diff.
 *
 * Runs as plain `node scripts/gen-registry.ts` (Node's built-in TypeScript
 * type stripping — no build step for this script itself). Keep it to
 * erasable syntax only: no enums, no namespaces, no parameter properties.
 */
import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import { gzipSync } from "node:zlib";

const GENERATED_HEADER =
  "// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.";

// ---------------------------------------------------------------------------
// Tools: src/tools/<category>/*.ts -> src/tools/index.ts
// ---------------------------------------------------------------------------

export interface ToolFileInfo {
  /** Directory name under src/tools/, e.g. "image". */
  category: string;
  /** Filename without extension, e.g. "jpg-to-png". */
  slug: string;
  /** Import specifier the generated barrel uses. */
  importPath: string;
  /** Generated identifier for the tool's default import. */
  varName: string;
}

/** kebab-case -> camelCase, for a generated default-import identifier. */
function toCamelCase(kebab: string): string {
  const camel = kebab.replace(/-([a-z0-9])/g, (_, c: string) =>
    c.toUpperCase(),
  );
  // A slug may start with a digit (see SLUG_RE in define-tool.ts); that
  // would make the camelCased result an invalid identifier on its own.
  return /^[0-9]/.test(camel) ? `_${camel}` : camel;
}

/**
 * Scans `src/tools/<category>/*.ts`, skipping `*.test.ts` and `index.ts`.
 * Returns an empty list if `src/tools/` doesn't exist yet — a fresh repo
 * with zero tools is a valid state (see `genToolsIndex`).
 *
 * Only paths are read here, never file contents — see the module doc
 * comment, "Static source scanning only".
 */
export function scanTools(rootDir: string): ToolFileInfo[] {
  const toolsDir = join(rootDir, "src", "tools");
  if (!existsSync(toolsDir)) return [];

  const categories = readdirSync(toolsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const infos: ToolFileInfo[] = [];
  const usedNames = new Set<string>();

  for (const category of categories) {
    const files = readdirSync(join(toolsDir, category), {
      withFileTypes: true,
    })
      .filter((d) => d.isFile() && d.name.endsWith(".ts"))
      .map((d) => d.name)
      .filter((name) => name !== "index.ts" && !name.endsWith(".test.ts"))
      .sort();

    for (const file of files) {
      const slug = file.slice(0, -".ts".length);
      const shortName = toCamelCase(slug);
      // Disambiguate a name collision across categories deterministically:
      // the first occurrence (sorted by category, then filename) keeps the
      // short name; a later collision gets the category folded in.
      const varName = usedNames.has(shortName)
        ? toCamelCase(`${category}-${slug}`)
        : shortName;
      usedNames.add(varName);
      infos.push({
        category,
        slug,
        importPath: `@/tools/${category}/${slug}`,
        varName,
      });
    }
  }

  return infos;
}

export function genToolsIndex(tools: readonly ToolFileInfo[]): string {
  const imports = tools.map(
    (t) => `import ${t.varName} from "${t.importPath}";`,
  );
  const list = tools.map((t) => t.varName).join(", ");

  return `${[
    GENERATED_HEADER,
    `import type { ToolDefinition } from "@/lib/registry";`,
    ...imports,
    "",
    `export const TOOLS: readonly ToolDefinition[] = [${list}];`,
    "",
    "export const TOOLS_BY_SLUG: ReadonlyMap<string, ToolDefinition> = new Map(",
    "  TOOLS.map((t) => [t.slug, t]),",
    ");",
  ].join("\n")}\n`;
}

/**
 * One catalog row's shape — mirrors the fields of `ToolDefinition`
 * (`src/lib/registry/types.ts`) that are plain, serialisable data: no zod
 * schema, no pipeline, no functions. This is what `genCatalog` writes to
 * `src/tools/catalog.ts` (ADR-0015): the universal from/to converter reads
 * this instead of the `TOOLS` barrel, so its home-page island never pays for
 * every tool's zod schema and pipeline.
 */
export interface ToolCatalogEntry {
  slug: string;
  title: string;
  category: string;
  accepts: readonly string[];
  produces: string;
  kind: "job" | "app";
  arity: "one-to-one" | "many-to-one" | "one-to-many";
  rank?: number;
  categoryRank?: number;
}

/**
 * Strips `/* ... *\/` and `// ...` comments before `parseToolCatalogEntry`'s
 * field regexes run over a tool file's source — a handful of tool files
 * mention a field's own name and value inside a doc comment (e.g.
 * `` `produces: "same"` `` in `strip-exif.ts`), and without this, a regex
 * matching the *first* occurrence of a key could latch onto the comment
 * instead of the real field. In every such case today the comment and the
 * real field happen to agree, but stripping comments first removes the
 * fragility rather than relying on that coincidence.
 */
function stripComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "");
}

function extractRequiredString(
  body: string,
  key: string,
  slug: string,
): string {
  const match = new RegExp(`\\b${key}:\\s*"((?:[^"\\\\]|\\\\.)*)"`).exec(body);
  if (!match) {
    throw new Error(
      `[gen-registry] tool "${slug}": could not find a "${key}: "..."" field`,
    );
  }
  return match[1] ?? "";
}

function extractOptionalString(body: string, key: string): string | null {
  const match = new RegExp(`\\b${key}:\\s*"((?:[^"\\\\]|\\\\.)*)"`).exec(body);
  return match ? (match[1] ?? "") : null;
}

function extractOptionalInt(body: string, key: string): number | undefined {
  const match = new RegExp(`\\b${key}:\\s*(\\d+)\\b`).exec(body);
  return match?.[1] !== undefined ? Number(match[1]) : undefined;
}

function extractStringArray(body: string, key: string, slug: string): string[] {
  const match = new RegExp(`\\b${key}:\\s*\\[([^\\]]*)\\]`).exec(body);
  if (!match) {
    throw new Error(
      `[gen-registry] tool "${slug}": could not find a "${key}: [...]" field`,
    );
  }
  const arrayBody = match[1] ?? "";
  const items: string[] = [];
  const itemRe = /"([^"]+)"/g;
  let itemMatch: RegExpExecArray | null;
  // biome-ignore lint/suspicious/noAssignInExpressions: standard RegExp.exec loop.
  while ((itemMatch = itemRe.exec(arrayBody)) !== null) {
    items.push(itemMatch[1] ?? "");
  }
  return items;
}

/**
 * Reads one tool file's literal `defineTool({...})` fields by text pattern,
 * never by importing or executing the file — see this module's doc comment,
 * "Static source scanning only". Every field this needs (`title`,
 * `category`, `accepts`, `produces`, `kind`, `arity`, `rank`) is always a
 * plain string, string array, or number literal in a tool file (never a
 * template literal or a `+`-concatenated string — `registry.test.ts` and
 * `defineTool` itself both assume the same), so a handful of targeted
 * regexes over the comment-stripped source is enough, the same "read text,
 * never import" spirit as this script's `engine.json` parsing above.
 */
export function parseToolCatalogEntry(
  info: ToolFileInfo,
  source: string,
): ToolCatalogEntry {
  const body = stripComments(source);

  const declaredSlug = extractOptionalString(body, "slug");
  if (declaredSlug !== info.slug) {
    throw new Error(
      `[gen-registry] tool "${info.slug}": declared slug ${JSON.stringify(declaredSlug)} does not match its filename`,
    );
  }
  const declaredCategory = extractOptionalString(body, "category");
  if (declaredCategory !== info.category) {
    throw new Error(
      `[gen-registry] tool "${info.slug}": declared category ${JSON.stringify(declaredCategory)} does not match its directory ("${info.category}")`,
    );
  }

  const title = extractRequiredString(body, "title", info.slug);
  const accepts = extractStringArray(body, "accepts", info.slug);
  const produces = extractRequiredString(body, "produces", info.slug);
  const kind = extractOptionalString(body, "kind");
  const arity = extractOptionalString(body, "arity");
  const rank = extractOptionalInt(body, "rank");
  const categoryRank = extractOptionalInt(body, "categoryRank");

  if (kind !== null && kind !== "job" && kind !== "app") {
    throw new Error(
      `[gen-registry] tool "${info.slug}": "kind" (${JSON.stringify(kind)}) must be "job" or "app"`,
    );
  }
  if (
    arity !== null &&
    arity !== "one-to-one" &&
    arity !== "many-to-one" &&
    arity !== "one-to-many"
  ) {
    throw new Error(
      `[gen-registry] tool "${info.slug}": "arity" (${JSON.stringify(arity)}) is not a known arity`,
    );
  }

  return {
    slug: info.slug,
    title,
    category: info.category,
    accepts,
    produces,
    kind: kind ?? "job",
    arity: (arity ?? "one-to-one") as ToolCatalogEntry["arity"],
    ...(rank !== undefined ? { rank } : {}),
    ...(categoryRank !== undefined ? { categoryRank } : {}),
  };
}

/** Reads and parses every scanned tool file's catalog fields — see
 * `parseToolCatalogEntry`'s doc comment on why this is text scanning, not
 * an import. */
export function scanToolCatalog(
  rootDir: string,
  tools: readonly ToolFileInfo[],
): ToolCatalogEntry[] {
  return tools.map((info) => {
    const filePath = join(
      rootDir,
      "src",
      "tools",
      info.category,
      `${info.slug}.ts`,
    );
    const source = readFileSync(filePath, "utf8");
    return parseToolCatalogEntry(info, source);
  });
}

export function genCatalog(entries: readonly ToolCatalogEntry[]): string {
  const rows = entries.map((e) => {
    const accepts = e.accepts.map((a) => `"${a}"`).join(", ");
    const rankPart =
      (e.rank !== undefined ? ` rank: ${e.rank},` : "") +
      (e.categoryRank !== undefined ? ` categoryRank: ${e.categoryRank},` : "");
    return (
      `  { slug: "${e.slug}", title: ${JSON.stringify(e.title)}, ` +
      `category: "${e.category}", accepts: [${accepts}], ` +
      `produces: "${e.produces}", kind: "${e.kind}", arity: "${e.arity}",${rankPart} },`
    );
  });
  const body = rows.length === 0 ? "[]" : `[\n${rows.join("\n")}\n]`;

  return `${[
    GENERATED_HEADER,
    `import type { Category } from "@/lib/registry/categories";`,
    `import type { FormatId } from "@/lib/registry/formats";`,
    "",
    "/**",
    " * ADR-0015: one row per tool, with only plain, serialisable data — no",
    " * zod schema, no pipeline, no functions. `src/lib/converter/catalog.ts`",
    " * builds the from/to picker's helpers over this instead of the `TOOLS`",
    " * barrel (`src/tools/index.ts`), which carries every tool's zod schema",
    " * and pipeline the home page must not pay for.",
    " */",
    "export interface CatalogEntry {",
    "  slug: string;",
    "  title: string;",
    "  category: Category;",
    "  accepts: readonly FormatId[];",
    '  produces: FormatId | "same";',
    '  kind: "job" | "app";',
    '  arity: "one-to-one" | "many-to-one" | "one-to-many";',
    "  /** 1 = most popular; unset = not featured — see `ToolDefinition.rank`. */",
    "  rank?: number;",
    "  /** 1 = first in its category's Popular row — see `ToolDefinition.categoryRank`. */",
    "  categoryRank?: number;",
    "}",
    "",
    `export const CATALOG: readonly CatalogEntry[] = ${body};`,
  ].join("\n")}\n`;
}

/**
 * Per-tool code splitting: a client page loads exactly one tool's module via
 * this map instead of importing the `TOOLS` barrel (which pulls in every
 * tool's pipeline and, transitively, its option schema — see
 * docs/ADDING_A_TOOL.md). Keyed by slug, which by convention **is** the
 * tool's file basename (`scanTools`'s `t.slug`) — `src/tools/registry.test.ts`
 * enforces that every tool's declared `slug` actually matches its filename,
 * which is what makes this map's keys trustworthy without importing the tool
 * modules here to check.
 */
export function genToolsLoaders(tools: readonly ToolFileInfo[]): string {
  const entries = tools.map(
    (t) => `  "${t.slug}": () => import("./${t.category}/${t.slug}"),`,
  );
  const body = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;

  return `${[
    GENERATED_HEADER,
    `import type { ToolDefinition } from "@/lib/registry";`,
    "",
    `export const TOOL_LOADERS = ${body} satisfies Record<`,
    "  string,",
    "  () => Promise<{ default: ToolDefinition }>",
    ">;",
  ].join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Engines: src/lib/engines/<id>/{engine.json,adapter.ts} -> ids.ts / manifest.ts / loaders.ts
// ---------------------------------------------------------------------------

const ENGINE_LOCATIONS = ["native", "static", "r2", "bundled"] as const;
type EngineLocationLike = (typeof ENGINE_LOCATIONS)[number];

export interface EngineAssetLike {
  path: string;
  bytes: number;
}

/** Mirrors `src/lib/engines/types.ts`'s `EngineSourceFile`. */
export interface EngineSourceFileLike {
  from: string;
  to: string;
  /** Overrides the engine's own `package` for this one file — see
   * `EngineSourceFile`'s doc comment in `src/lib/engines/types.ts`. */
  package?: string;
  /** Ships gzipped — see `EngineSourceFile.gzip`'s doc comment. Sized here
   * (`resolveAssets`) by actually gzipping the source bytes, so
   * `ENGINE_MANIFEST`'s `totalBytes` reflects what `sync-engines` really
   * ships, not the uncompressed source's size. */
  gzip?: boolean;
}

/**
 * The structural shape of one `engine.json`, validated but not yet resolved:
 * `version` isn't known for real yet for a "static"/"r2" engine (derived
 * from the installed `package`'s version) or a "bundled" engine with
 * `versionFrom` set (derived from *that* package). `scanEngines` is what
 * resolves those, via `resolveVersion`/`resolveAssets` below, into the final
 * `EngineMetaLike` `pnpm gen`'s codegen functions consume.
 */
export interface EngineSourceMeta {
  id: string;
  license: string;
  location: EngineLocationLike;
  needsIsolation: boolean;
  heavy: boolean;
  /**
   * "job" (the default): a one-shot `EngineAdapter` the job pipeline can
   * dispatch a `run(task)` to — needs `adapter.ts` alongside `engine.json`,
   * and is included in the `EngineId` union, `ENGINE_LOADERS`, and every
   * pipeline step's engine candidates.
   *
   * "session": a stateful engine an app-mode tool owns directly (e.g.
   * pdfium, driven by the PDF editor) — no `adapter.ts`, no one-shot
   * `run(task)` shape fits it. Excluded from `EngineId`/`ENGINE_LOADERS`/the
   * job pipeline entirely, but still included in `ENGINE_MANIFEST` (derived
   * version, assets, baseUrl) and still copied by `sync-engines`, so a
   * version bump of its npm package is zero-maintenance the same way a job
   * engine's is.
   */
  kind: "job" | "session";
  /**
   * ADR-0002 rule 4: gate this engine's first download behind an explicit
   * consent prompt (see `src/lib/engines/consent.ts`). Optional in
   * `engine.json`, defaults to `false` — set `true` only for an engine whose
   * download is large and/or non-permissively licensed (e.g. `ffmpeg`).
   */
  consent?: boolean;
  /**
   * Hand-written version. Required for "native" (wraps a browser API — no
   * installed package to derive from) and for "bundled" without
   * `versionFrom` (our own code, e.g. `exif`). Forbidden for "static"/"r2"
   * (always derived from `package`) and for "bundled" with `versionFrom`.
   */
  version?: string;
  /**
   * "bundled" only: the npm package whose installed version stands in for
   * this engine's own — e.g. `heic` ships our adapter around `heic-to`, so
   * its version tracks `heic-to`'s. Mutually exclusive with `version`.
   */
  versionFrom?: string;
  /** Required iff `location` is "static" or "r2"; forbidden otherwise — see `parseEngineMeta`. */
  package?: string;
  files?: readonly EngineSourceFileLike[];
}

/**
 * `EngineSourceMeta` plus what `scanEngines` resolves against installed
 * node_modules packages: a real semver `version` and each declared file's
 * real size on disk. Mirrors `src/lib/engines/meta.ts`'s `EngineMeta` (with
 * `assets` filled in) — this is the shape `genEngineIds`/`genEngineManifest`/
 * `genEngineLoaders` consume.
 */
export interface EngineMetaLike extends EngineSourceMeta {
  version: string;
  assets: readonly EngineAssetLike[];
}

const SEMVER_RE = /^\d+\.\d+\.\d+([-+][0-9A-Za-z.-]+)?$/;

/**
 * Parses and validates one engine directory's `engine.json` text against
 * the contract in `src/lib/engines/meta.ts`. Pure structural validation only
 * — no filesystem access beyond the string already read, so no `rootDir` is
 * needed here. Throws a `[gen-registry] engine "<dir>": ...` message on any
 * violation.
 */
export function parseEngineMeta(
  dirName: string,
  rawJson: string,
): EngineSourceMeta {
  const fail = (message: string): never => {
    throw new Error(`[gen-registry] engine "${dirName}": ${message}`);
  };

  const parsed: unknown = JSON.parse(rawJson);
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    fail("engine.json must be a JSON object");
  }
  const j = parsed as Record<string, unknown>;

  if (typeof j.id !== "string" || j.id === "") {
    fail(`"id" must be a non-empty string`);
  }
  if (j.id !== dirName) {
    fail(
      `"id" ("${String(j.id)}") must match its directory name ("${dirName}")`,
    );
  }
  if (typeof j.license !== "string" || j.license.trim() === "") {
    fail(`"license" must be a non-empty string`);
  }
  if (
    typeof j.location !== "string" ||
    !(ENGINE_LOCATIONS as readonly string[]).includes(j.location)
  ) {
    fail(
      `"location" (${JSON.stringify(j.location)}) must be one of ${ENGINE_LOCATIONS.join(", ")}`,
    );
  }
  const location = j.location as EngineLocationLike;
  if (typeof j.needsIsolation !== "boolean") {
    fail(`"needsIsolation" must be a boolean`);
  }
  if (typeof j.heavy !== "boolean") {
    fail(`"heavy" must be a boolean`);
  }
  if (j.assets !== undefined) {
    fail(
      `"assets" is not allowed in engine.json — sizes are computed by "pnpm gen" from the installed package`,
    );
  }
  if (j.kind !== undefined && j.kind !== "job" && j.kind !== "session") {
    fail(`"kind" must be "job" or "session"`);
  }
  const kind: "job" | "session" = j.kind === "session" ? "session" : "job";
  if (j.consent !== undefined && typeof j.consent !== "boolean") {
    fail(`"consent" must be a boolean`);
  }
  const consent = j.consent === true;

  // "package"/"files" name the npm package and files `sync-engines` copies
  // the engine's assets from, and (for "static"/"r2") the package
  // `scanEngines` derives this engine's version from — meaningless for
  // "native" (wraps a browser API) or "bundled" (pure JS in the engine's own
  // worker chunk), neither of which ships assets of its own.
  const needsSource = location === "static" || location === "r2";
  let pkg: string | undefined;
  let files: EngineSourceFileLike[] | undefined;

  if (needsSource) {
    if (typeof j.package !== "string" || j.package.trim() === "") {
      fail(`"package" is required when location is "${location}"`);
    }
    pkg = j.package as string;

    if (!Array.isArray(j.files) || j.files.length === 0) {
      fail(
        `"files" is required when location is "${location}" and must be a non-empty array`,
      );
    }
    files = (j.files as unknown[]).map((f, i) => {
      if (typeof f !== "object" || f === null) {
        fail(`"files[${i}]" must be an object`);
      }
      const file = f as Record<string, unknown>;
      if (typeof file.from !== "string" || file.from === "") {
        fail(`"files[${i}].from" must be a non-empty string`);
      }
      if (typeof file.to !== "string" || file.to === "") {
        fail(`"files[${i}].to" must be a non-empty string`);
      }
      if (file.package !== undefined && typeof file.package !== "string") {
        fail(`"files[${i}].package" must be a string`);
      }
      if (file.gzip !== undefined && typeof file.gzip !== "boolean") {
        fail(`"files[${i}].gzip" must be a boolean`);
      }
      return {
        from: file.from as string,
        to: file.to as string,
        ...(file.package !== undefined
          ? { package: file.package as string }
          : {}),
        ...(file.gzip !== undefined ? { gzip: file.gzip as boolean } : {}),
      };
    });
  } else {
    if (j.package !== undefined) {
      fail(`"package" is not allowed when location is "${location}"`);
    }
    if (j.files !== undefined) {
      fail(`"files" is not allowed when location is "${location}"`);
    }
  }

  // version / versionFrom: exactly one source of truth per location.
  let version: string | undefined;
  let versionFrom: string | undefined;

  if (needsSource) {
    if (j.version !== undefined) {
      fail(
        `"version" is not allowed when location is "${location}" — it is derived from the installed "package" version`,
      );
    }
    if (j.versionFrom !== undefined) {
      fail(`"versionFrom" is not allowed when location is "${location}"`);
    }
  } else if (location === "bundled") {
    const hasVersion = j.version !== undefined;
    const hasVersionFrom = j.versionFrom !== undefined;
    if (hasVersion === hasVersionFrom) {
      fail(
        `a "bundled" engine needs exactly one of "version" (our own code) or "versionFrom" (an npm package whose version we track)`,
      );
    }
    if (hasVersion) {
      if (typeof j.version !== "string" || !SEMVER_RE.test(j.version)) {
        fail(
          `"version" (${JSON.stringify(j.version)}) must be semver, e.g. "1.0.0"`,
        );
      }
      version = j.version as string;
    } else {
      if (typeof j.versionFrom !== "string" || j.versionFrom.trim() === "") {
        fail(`"versionFrom" must be a non-empty string`);
      }
      versionFrom = j.versionFrom as string;
    }
  } else {
    // "native"
    if (j.versionFrom !== undefined) {
      fail(`"versionFrom" is not allowed when location is "native"`);
    }
    if (typeof j.version !== "string" || !SEMVER_RE.test(j.version)) {
      fail(
        `"version" (${JSON.stringify(j.version)}) must be semver, e.g. "1.0.0"`,
      );
    }
    version = j.version as string;
  }

  return {
    id: j.id as string,
    license: j.license as string,
    location,
    needsIsolation: j.needsIsolation as boolean,
    heavy: j.heavy as boolean,
    kind,
    consent,
    ...(version !== undefined ? { version } : {}),
    ...(versionFrom !== undefined ? { versionFrom } : {}),
    ...(pkg !== undefined && files !== undefined
      ? { package: pkg, files }
      : {}),
  };
}

/**
 * Resolves an installed npm package's on-disk directory. Tries
 * `require.resolve` first (works even for a package whose `exports` map
 * happens to expose `./package.json`); a package whose `exports` blocks that
 * subpath makes `require.resolve` throw even though the package is
 * installed, so this falls back to the conventional `node_modules/<pkg>`
 * layout. `paths: [rootDir]` — rather than resolving relative to this
 * script's own location — is what makes this testable against a fixture
 * `rootDir` with its own `node_modules`.
 *
 * Duplicated from `scripts/sync-engines.ts`'s function of the same name
 * rather than imported — see this file's module doc comment, "Static source
 * scanning only", on why this script imports nothing of our own.
 */
export function resolvePackageDir(pkg: string, rootDir: string): string {
  const require = createRequire(import.meta.url);
  try {
    return dirname(
      require.resolve(`${pkg}/package.json`, { paths: [rootDir] }),
    );
  } catch {
    const fallback = join(rootDir, "node_modules", ...pkg.split("/"));
    if (existsSync(join(fallback, "package.json"))) return fallback;
    throw new Error(
      `[gen-registry] cannot resolve package "${pkg}" from ${rootDir} — is it installed?`,
    );
  }
}

function readInstalledVersion(packageDir: string, dirName: string): string {
  const pkgJsonPath = join(packageDir, "package.json");
  const pkgJson = JSON.parse(readFileSync(pkgJsonPath, "utf8")) as {
    version?: unknown;
  };
  if (typeof pkgJson.version !== "string") {
    throw new Error(
      `[gen-registry] engine "${dirName}": "${pkgJsonPath}" has no "version" field`,
    );
  }
  return pkgJson.version;
}

/**
 * Every regular file under `dir`, recursively, as POSIX-style paths relative
 * to `dir` (e.g. `"nested/Foo.bcmap"`) — used by `resolveAssets`'s
 * directory-entry support below, mirroring
 * `scripts/sync-engines.ts`'s function of the same name.
 */
function listFilesRecursive(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      for (const rel of listFilesRecursive(join(dir, entry.name))) {
        out.push(`${entry.name}/${rel}`);
      }
    } else if (entry.isFile()) {
      out.push(entry.name);
    }
  }
  return out;
}

/**
 * Resolves one engine's real version: hand-written for "native" and for
 * "bundled" without `versionFrom`; otherwise read off the installed npm
 * package's own `package.json` (`package` for "static"/"r2", `versionFrom`
 * for "bundled" with it set).
 */
function resolveVersion(
  dirName: string,
  source: EngineSourceMeta,
  rootDir: string,
): string {
  if (source.location === "static" || source.location === "r2") {
    return readInstalledVersion(
      resolvePackageDir(source.package as string, rootDir),
      dirName,
    );
  }
  if (source.location === "bundled" && source.versionFrom !== undefined) {
    return readInstalledVersion(
      resolvePackageDir(source.versionFrom, rootDir),
      dirName,
    );
  }
  // "native", or "bundled" without versionFrom — parseEngineMeta guarantees
  // `version` is set in both remaining cases.
  return source.version as string;
}

/**
 * Resolves one "static"/"r2" engine's real asset sizes by `stat`ing each
 * declared file directly in its source npm package — no copying needed, so
 * this can run before (or without) `pnpm sync-engines`. Empty for "native"/
 * "bundled", which ship no assets of their own. Mirrors
 * `scripts/sync-engines.ts`'s `copyEngineFiles`, minus the actual copy.
 */
function resolveAssets(
  dirName: string,
  source: EngineSourceMeta,
  rootDir: string,
): EngineAssetLike[] {
  if (source.location !== "static" && source.location !== "r2") return [];

  const fail = (message: string): never => {
    throw new Error(`[gen-registry] engine "${dirName}": ${message}`);
  };

  const packageDir = resolvePackageDir(source.package as string, rootDir);
  const packageDirs = new Map<string, string>([
    [source.package as string, packageDir],
  ]);
  const resolveFilePackageDir = (fileSource: EngineSourceFileLike): string => {
    if (fileSource.package === undefined) return packageDir;
    // "local" sentinel — see the identical comment in
    // `scripts/sync-engines.ts`'s `copyEngineFiles`.
    if (fileSource.package === "local") return rootDir;
    const cached = packageDirs.get(fileSource.package);
    if (cached) return cached;
    const resolved = resolvePackageDir(fileSource.package, rootDir);
    packageDirs.set(fileSource.package, resolved);
    return resolved;
  };

  const assets: EngineAssetLike[] = [];
  for (const fileSource of source.files ?? []) {
    const { from, to } = fileSource;
    if (from.endsWith("/") !== to.endsWith("/")) {
      fail(
        `a directory entry's "from" and "to" must both end with "/" (got from="${from}", to="${to}")`,
      );
    }
    const fromPackageDir = resolveFilePackageDir(fileSource);

    if (from.endsWith("/")) {
      const srcDir = join(fromPackageDir, ...from.split("/"));
      for (const rel of listFilesRecursive(srcDir)) {
        const bytes = statSync(join(srcDir, ...rel.split("/"))).size;
        assets.push({ path: `${to}${rel}`, bytes });
      }
      continue;
    }

    const srcPath = join(fromPackageDir, ...from.split("/"));
    // Sized post-gzip, matching what `sync-engines`'s `copyOneFile` actually
    // writes — see `EngineSourceFileLike.gzip`'s doc comment. Everything
    // else here still only `statSync`s (cheap); only a `gzip: true` file
    // pays for reading + compressing its full source bytes.
    const bytes = fileSource.gzip
      ? gzipSync(readFileSync(srcPath), { level: 9 }).length
      : statSync(srcPath).size;
    assets.push({ path: to, bytes });
  }
  return assets.sort((a, b) => a.path.localeCompare(b.path));
}

/**
 * Throws if two engines share an `id`. Structurally this can't happen via
 * `scanEngines` alone (a directory's `id` must equal its own, necessarily
 * unique, directory name — see `parseEngineMeta`), but it's cheap defensive
 * validation, and it's exposed separately so it can be exercised directly
 * with hand-built `EngineMetaLike`s, no filesystem required.
 */
export function assertNoDuplicateIds(metas: readonly EngineMetaLike[]): void {
  const seen = new Set<string>();
  for (const meta of metas) {
    if (seen.has(meta.id)) {
      throw new Error(`[gen-registry] duplicate engine id "${meta.id}"`);
    }
    seen.add(meta.id);
  }
}

/**
 * Scans `src/lib/engines/<id>/`. A subdirectory counts as an engine only
 * once it has *both* `engine.json` and `adapter.ts` — one without the other
 * is a broken engine directory and fails generation, since it's plausibly
 * a half-finished `add-engine` in progress rather than something to skip
 * silently. A subdirectory with neither file (unrelated to an engine) is
 * ignored.
 */
export function scanEngines(rootDir: string): EngineMetaLike[] {
  const enginesDir = join(rootDir, "src", "lib", "engines");
  if (!existsSync(enginesDir)) return [];

  const dirNames = readdirSync(enginesDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const metas: EngineMetaLike[] = [];

  for (const dirName of dirNames) {
    const dir = join(enginesDir, dirName);
    const hasJson = existsSync(join(dir, "engine.json"));
    const hasAdapter = existsSync(join(dir, "adapter.ts"));

    if (!hasJson && !hasAdapter) continue;

    if (hasAdapter && !hasJson) {
      throw new Error(
        `[gen-registry] engine "${dirName}" has adapter.ts but no engine.json`,
      );
    }

    const rawJson = readFileSync(join(dir, "engine.json"), "utf8");
    const source = parseEngineMeta(dirName, rawJson);

    // A "job" engine needs `adapter.ts` — the job pipeline dispatches a
    // one-shot `run(task)` to it. A "session" engine (e.g. pdfium) is a
    // stateful engine an app-mode tool drives directly; it must NOT have
    // one, so it never leaks into `EngineId`/`ENGINE_LOADERS` by accident.
    if (source.kind === "session" && hasAdapter) {
      throw new Error(
        `[gen-registry] engine "${dirName}" is kind "session" and must not have adapter.ts — session engines are excluded from the job pipeline`,
      );
    }
    if (source.kind !== "session" && !hasAdapter) {
      throw new Error(
        `[gen-registry] engine "${dirName}" has engine.json but no adapter.ts`,
      );
    }

    const version = resolveVersion(dirName, source, rootDir);
    const assets = resolveAssets(dirName, source, rootDir);
    metas.push({ ...source, version, assets });
  }

  assertNoDuplicateIds(metas);
  return metas;
}

/**
 * Duplicated from `src/lib/engines/meta.ts`'s `engineBaseUrl` rather than
 * imported — see the module doc comment on why this script imports nothing
 * of our own.
 */
function engineBaseUrl(
  id: string,
  version: string,
  location: EngineLocationLike,
): string {
  // Tried percent-encoding the literal "@" here once (Cloudflare's Workers
  // Static Assets 307-redirects an unencoded "@" to its encoded form, so
  // every engine asset pays one avoidable extra round trip in production)
  // — reverted: Vite's dev server (vitest.browser.config.ts's browser-mode
  // tests) and Next's own dev server resolve `public/`'s literal, unencoded
  // "pdfjs@6.3.289" directory name and 404 on the encoded form instead of
  // decoding it, so encoding here traded a small prod-only round trip for a
  // broken local dev/test story across every static/r2 engine. Fixed
  // instead by dropping "@" from the path entirely — see `--` below.
  //
  // `--` is the id/version delimiter: URL-safe (no redirect anywhere, no
  // encoding mismatch between prod and dev servers) and unambiguous to
  // split back apart with `lastIndexOf("--")`, since engine ids use single
  // hyphens only (e.g. "jsquash-jpeg") and semver versions never contain a
  // double hyphen either.
  switch (location) {
    case "native":
    case "bundled":
      return "";
    case "static":
      return `/engines/${id}--${version}/`;
    case "r2":
      return `/engines/xl/${id}--${version}/`;
  }
}

function sortedById<T extends { id: string }>(metas: readonly T[]): T[] {
  return [...metas].sort((a, b) => a.id.localeCompare(b.id));
}

const VALID_IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * An engine id as an object property key: bare when it's a valid JS
 * identifier (matches what `pnpm gen`'s own `biome check --write` pass would
 * settle on anyway, under its default `quoteProperties: "asNeeded"`),
 * quoted otherwise. Most engine ids are hyphenated (`jsquash-jpeg`), which
 * is not a valid identifier — `${m.id}: {` would parse as a subtraction
 * expression, not a property name, so this can't just interpolate `m.id`
 * unquoted the way `genToolsIndex`'s import identifiers can.
 */
function propKey(id: string): string {
  return VALID_IDENTIFIER_RE.test(id) ? id : JSON.stringify(id);
}

/** "session" engines (e.g. pdfium) are excluded from `EngineId` — the job
 * pipeline never dispatches to them. See `EngineSourceMeta.kind`. */
export function genEngineIds(metas: readonly EngineMetaLike[]): string {
  const ids = metas
    .filter((m) => m.kind !== "session")
    .map((m) => m.id)
    .sort();
  const union =
    ids.length === 0 ? "never" : ids.map((id) => `"${id}"`).join(" | ");
  return `${GENERATED_HEADER}\nexport type EngineId = ${union};\n`;
}

export function genEngineManifest(metas: readonly EngineMetaLike[]): string {
  const entries = sortedById(metas).map((m) => {
    const totalBytes = m.assets.reduce((sum, a) => sum + a.bytes, 0);
    const baseUrl = engineBaseUrl(m.id, m.version, m.location);
    const assets = m.assets
      .map((a) => `{ path: "${a.path}", bytes: ${a.bytes} }`)
      .join(", ");
    return [
      `  ${propKey(m.id)}: {`,
      `    id: "${m.id}",`,
      `    version: "${m.version}",`,
      `    license: "${m.license}",`,
      `    location: "${m.location}",`,
      `    needsIsolation: ${m.needsIsolation},`,
      `    heavy: ${m.heavy},`,
      `    kind: "${m.kind}",`,
      `    consent: ${m.consent},`,
      `    assets: [${assets}],`,
      `    baseUrl: "${baseUrl}",`,
      `    totalBytes: ${totalBytes},`,
      "  },",
    ].join("\n");
  });

  const body = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;

  return `${[
    GENERATED_HEADER,
    `import type { EngineManifestEntry } from "./meta";`,
    "",
    `export const ENGINE_MANIFEST = ${body} as const satisfies Record<`,
    "  string,",
    "  EngineManifestEntry",
    ">;",
  ].join("\n")}\n`;
}

/** "session" engines have no `adapter.ts` — excluded, same as `genEngineIds`. */
export function genEngineLoaders(metas: readonly EngineMetaLike[]): string {
  const entries = sortedById(metas)
    .filter((m) => m.kind !== "session")
    .map((m) => `  ${propKey(m.id)}: () => import("./${m.id}/adapter"),`);
  const body = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;

  return `${[
    GENERATED_HEADER,
    "/**",
    " * WORKER-ONLY. Only a worker may import this module — importing it from",
    " * main-thread code would pull every engine adapter into the core bundle",
    ' * (see docs/ARCHITECTURE.md, "Engines"); `check-sizes` would catch it.',
    " */",
    `import type { EngineAdapter } from "./types";`,
    `import type { EngineId } from "./ids";`,
    "",
    `export const ENGINE_LOADERS = ${body} satisfies Record<`,
    "  EngineId,",
    "  () => Promise<{ default: EngineAdapter }>",
    ">;",
  ].join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Orchestration
// ---------------------------------------------------------------------------

/**
 * Pure: scans `rootDir` and returns the full set of generated files, keyed
 * by path relative to `rootDir` (forward slashes, regardless of platform).
 * Deterministic — calling this twice against the same `rootDir` produces
 * identical output. `main()` is the only impure part: it writes these to
 * disk and runs Biome over them.
 */
export function generate(rootDir: string): Map<string, string> {
  const tools = scanTools(rootDir);
  const catalog = scanToolCatalog(rootDir, tools);
  const engines = scanEngines(rootDir);

  return new Map([
    ["src/tools/index.ts", genToolsIndex(tools)],
    ["src/tools/loaders.ts", genToolsLoaders(tools)],
    ["src/tools/catalog.ts", genCatalog(catalog)],
    ["src/lib/engines/ids.ts", genEngineIds(engines)],
    ["src/lib/engines/manifest.ts", genEngineManifest(engines)],
    ["src/lib/engines/loaders.ts", genEngineLoaders(engines)],
  ]);
}

function main(): void {
  const rootDir = process.cwd();

  let files: Map<string, string>;
  try {
    files = generate(rootDir);
  } catch (e) {
    console.error(e instanceof Error ? e.message : String(e));
    process.exit(1);
  }

  const writtenPaths: string[] = [];
  for (const [relPath, content] of files) {
    const fullPath = join(rootDir, relPath);
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, content);
    writtenPaths.push(fullPath);
  }

  // Formats and lint-fixes the output in place, so `pnpm gen` alone produces
  // final, `pnpm lint`-clean files — CI runs `pnpm gen` and fails on any
  // diff, so this step can't be a separate manual "remember to lint" step.
  const biomeBin = join(
    rootDir,
    "node_modules",
    "@biomejs",
    "biome",
    "bin",
    "biome",
  );
  execFileSync(
    process.execPath,
    [biomeBin, "check", "--write", ...writtenPaths],
    {
      stdio: "inherit",
    },
  );

  // biome-ignore lint/suspicious/noConsole: pnpm gen's own completion summary.
  console.log(`gen-registry: wrote ${writtenPaths.length} file(s).`);
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main();
}
