import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  assertNoDuplicateIds,
  type EngineMetaLike,
  genEngineIds,
  genEngineLoaders,
  genEngineManifest,
  generate,
  genToolsIndex,
  parseEngineMeta,
  scanEngines,
  scanTools,
} from "./gen-registry";

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

const tempDirs: string[] = [];

/** A fresh temp directory, cleaned up in `afterEach`. */
function makeTempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "gen-registry-test-"));
  tempDirs.push(dir);
  return dir;
}

afterEach(() => {
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

function writeFile(rootDir: string, relPath: string, content: string): void {
  const fullPath = join(rootDir, ...relPath.split("/"));
  mkdirSync(join(fullPath, ".."), { recursive: true });
  writeFileSync(fullPath, content);
}

/**
 * Default `location` is "static", so `package`/`files` are included by
 * default too — otherwise every existing call site unrelated to those two
 * new fields would fail validation for the wrong reason. A caller that wants
 * a "native" engine.json (no `package`/`files` allowed) overrides both to
 * `undefined`, which `JSON.stringify` drops from the merged object entirely.
 */
function engineJson(overrides: Partial<Record<string, unknown>> = {}): string {
  return JSON.stringify({
    id: "foo",
    version: "1.0.0",
    license: "MIT",
    location: "static",
    package: "@acme/foo",
    files: [{ from: "foo.wasm", to: "foo.wasm" }],
    needsIsolation: false,
    heavy: false,
    assets: [],
    ...overrides,
  });
}

/**
 * A fixture with two tools (in different categories) and three engines, one
 * per `location` — the shape most of the tests below scan.
 */
function makeFullFixture(): string {
  const dir = makeTempDir();

  writeFile(dir, "src/tools/image/a-to-b.ts", "export default {};\n");
  writeFile(dir, "src/tools/image/a-to-b.test.ts", "// skipped\n");
  writeFile(dir, "src/tools/image/index.ts", "// skipped\n");
  writeFile(dir, "src/tools/pdf/merge-pdf.ts", "export default {};\n");

  writeFile(
    dir,
    "src/lib/engines/bar/engine.json",
    engineJson({
      id: "bar",
      location: "native",
      package: undefined,
      files: undefined,
    }),
  );
  writeFile(dir, "src/lib/engines/bar/adapter.ts", "export default {};\n");

  writeFile(
    dir,
    "src/lib/engines/baz/engine.json",
    engineJson({
      id: "baz",
      version: "2.1.0",
      license: "Apache-2.0",
      location: "r2",
      package: "@acme/baz",
      files: [
        { from: "codec/baz.wasm", to: "baz.wasm" },
        { from: "codec/baz.data", to: "baz.data" },
      ],
      needsIsolation: true,
      heavy: true,
      assets: [
        { path: "baz.wasm", bytes: 2000 },
        { path: "baz.data", bytes: 500 },
      ],
    }),
  );
  writeFile(dir, "src/lib/engines/baz/adapter.ts", "export default {};\n");

  writeFile(
    dir,
    "src/lib/engines/foo/engine.json",
    engineJson({
      id: "foo",
      version: "1.2.3",
      location: "static",
      assets: [{ path: "foo.wasm", bytes: 1024 }],
    }),
  );
  writeFile(dir, "src/lib/engines/foo/adapter.ts", "export default {};\n");

  return dir;
}

function get(files: Map<string, string>, path: string): string {
  return files.get(path) ?? "";
}

// ---------------------------------------------------------------------------
// scanTools / genToolsIndex
// ---------------------------------------------------------------------------

describe("scanTools", () => {
  it("returns an empty list when src/tools doesn't exist", () => {
    expect(scanTools(makeTempDir())).toEqual([]);
  });

  it("skips *.test.ts and index.ts", () => {
    const dir = makeFullFixture();
    const slugs = scanTools(dir).map((t) => t.slug);
    expect(slugs).not.toContain("a-to-b.test");
    expect(slugs).not.toContain("index");
  });

  it("sorts by category then filename", () => {
    const dir = makeFullFixture();
    const tools = scanTools(dir);
    expect(tools.map((t) => `${t.category}/${t.slug}`)).toEqual([
      "image/a-to-b",
      "pdf/merge-pdf",
    ]);
  });
});

describe("genToolsIndex", () => {
  it("emits an empty, still-valid TOOLS array for zero tools", () => {
    const out = genToolsIndex([]);
    expect(out).toContain(
      "export const TOOLS: readonly ToolDefinition[] = [];",
    );
    expect(out).toContain(
      "// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.",
    );
  });

  it("emits a sorted, camelCased default import per tool", () => {
    const dir = makeFullFixture();
    const out = genToolsIndex(scanTools(dir));
    expect(out).toContain('import aToB from "@/tools/image/a-to-b";');
    expect(out).toContain('import mergePdf from "@/tools/pdf/merge-pdf";');
    expect(out).toContain(
      "export const TOOLS: readonly ToolDefinition[] = [aToB, mergePdf];",
    );
    expect(out).toContain(
      "export const TOOLS_BY_SLUG: ReadonlyMap<string, ToolDefinition> = new Map(",
    );
  });
});

// ---------------------------------------------------------------------------
// parseEngineMeta / scanEngines validation
// ---------------------------------------------------------------------------

describe("parseEngineMeta", () => {
  it("parses a valid engine.json", () => {
    const meta = parseEngineMeta("foo", engineJson());
    expect(meta).toEqual({
      id: "foo",
      version: "1.0.0",
      license: "MIT",
      location: "static",
      needsIsolation: false,
      heavy: false,
      assets: [],
      package: "@acme/foo",
      files: [{ from: "foo.wasm", to: "foo.wasm" }],
    });
  });

  it("parses a native engine.json with no package/files", () => {
    const meta = parseEngineMeta(
      "foo",
      engineJson({ location: "native", package: undefined, files: undefined }),
    );
    expect(meta).toEqual({
      id: "foo",
      version: "1.0.0",
      license: "MIT",
      location: "native",
      needsIsolation: false,
      heavy: false,
      assets: [],
    });
  });

  it("rejects an id that doesn't match the directory name", () => {
    expect(() => parseEngineMeta("foo", engineJson({ id: "wrong" }))).toThrow(
      /"id".*must match its directory name/,
    );
  });

  it("rejects an unknown location", () => {
    expect(() =>
      parseEngineMeta("foo", engineJson({ location: "cdn" })),
    ).toThrow(/"location".*must be one of/);
  });

  it("rejects a non-semver version", () => {
    expect(() => parseEngineMeta("foo", engineJson({ version: "v1" }))).toThrow(
      /"version".*must be semver/,
    );
  });

  it("rejects a non-boolean needsIsolation", () => {
    expect(() =>
      parseEngineMeta("foo", engineJson({ needsIsolation: "yes" })),
    ).toThrow(/"needsIsolation" must be a boolean/);
  });

  it.each(["static", "r2"] as const)(
    'requires "package" when location is "%s"',
    (location) => {
      expect(() =>
        parseEngineMeta("foo", engineJson({ location, package: undefined })),
      ).toThrow(/"package" is required when location is/);
    },
  );

  it.each(["static", "r2"] as const)(
    'requires "files" when location is "%s"',
    (location) => {
      expect(() =>
        parseEngineMeta("foo", engineJson({ location, files: undefined })),
      ).toThrow(/"files" is required when location is/);
    },
  );

  it('rejects an empty "files" array', () => {
    expect(() => parseEngineMeta("foo", engineJson({ files: [] }))).toThrow(
      /"files" is required.*non-empty array/,
    );
  });

  it('rejects a "files" entry missing "to"', () => {
    expect(() =>
      parseEngineMeta("foo", engineJson({ files: [{ from: "x.wasm" }] })),
    ).toThrow(/"files\[0\]\.to" must be a non-empty string/);
  });

  it('forbids "package" when location is "native"', () => {
    expect(() =>
      parseEngineMeta(
        "foo",
        engineJson({ location: "native", files: undefined }),
      ),
    ).toThrow(/"package" is not allowed when location is "native"/);
  });

  it('forbids "files" when location is "native"', () => {
    expect(() =>
      parseEngineMeta(
        "foo",
        engineJson({ location: "native", package: undefined }),
      ),
    ).toThrow(/"files" is not allowed when location is "native"/);
  });
});

describe("scanEngines", () => {
  it("returns an empty list when src/lib/engines doesn't exist", () => {
    expect(scanEngines(makeTempDir())).toEqual([]);
  });

  it("ignores a subdirectory with neither engine.json nor adapter.ts", () => {
    const dir = makeTempDir();
    writeFile(dir, "src/lib/engines/scratch/notes.txt", "wip\n");
    expect(scanEngines(dir)).toEqual([]);
  });

  it("errors when a directory has engine.json but no adapter.ts", () => {
    const dir = makeTempDir();
    writeFile(dir, "src/lib/engines/foo/engine.json", engineJson());
    expect(() => scanEngines(dir)).toThrow(
      /engine "foo" has engine\.json but no adapter\.ts/,
    );
  });

  it("errors when a directory has adapter.ts but no engine.json", () => {
    const dir = makeTempDir();
    writeFile(dir, "src/lib/engines/foo/adapter.ts", "export default {};\n");
    expect(() => scanEngines(dir)).toThrow(
      /engine "foo" has adapter\.ts but no engine\.json/,
    );
  });

  it("returns metadata for every valid engine directory, sorted", () => {
    const dir = makeFullFixture();
    expect(scanEngines(dir).map((m) => m.id)).toEqual(["bar", "baz", "foo"]);
  });
});

describe("assertNoDuplicateIds", () => {
  function meta(id: string): EngineMetaLike {
    return {
      id,
      version: "1.0.0",
      license: "MIT",
      location: "native",
      needsIsolation: false,
      heavy: false,
      assets: [],
    };
  }

  it("does not throw for unique ids", () => {
    expect(() =>
      assertNoDuplicateIds([meta("foo"), meta("bar")]),
    ).not.toThrow();
  });

  it("throws when two engines share an id", () => {
    expect(() => assertNoDuplicateIds([meta("foo"), meta("foo")])).toThrow(
      /duplicate engine id "foo"/,
    );
  });
});

// ---------------------------------------------------------------------------
// genEngineIds / genEngineManifest / genEngineLoaders
// ---------------------------------------------------------------------------

describe("genEngineIds", () => {
  it("is 'never' for zero engines", () => {
    expect(genEngineIds([])).toContain("export type EngineId = never;");
  });

  it("unions ids alphabetically", () => {
    const dir = makeFullFixture();
    const out = genEngineIds(scanEngines(dir));
    expect(out).toContain('export type EngineId = "bar" | "baz" | "foo";');
  });
});

describe("genEngineManifest", () => {
  it("is an empty, still-valid manifest for zero engines", () => {
    const out = genEngineManifest([]);
    expect(out).toContain(
      "export const ENGINE_MANIFEST = {} as const satisfies Record<",
    );
  });

  it('never contains the substring "adapter" — main-thread-safe, no adapter import', () => {
    const dir = makeFullFixture();
    const out = genEngineManifest(scanEngines(dir));
    expect(out).not.toContain("adapter");
  });

  it("omits package/files — the main thread doesn't need them", () => {
    const dir = makeFullFixture();
    const out = genEngineManifest(scanEngines(dir));
    expect(out).not.toContain("package");
    expect(out).not.toContain("files");
  });

  it("computes baseUrl per location", () => {
    const dir = makeFullFixture();
    const out = genEngineManifest(scanEngines(dir));
    expect(out).toContain('baseUrl: "",'); // bar: native
    expect(out).toContain('baseUrl: "/engines/foo@1.2.3/",'); // foo: static
    expect(out).toContain('baseUrl: "/engines/xl/baz@2.1.0/",'); // baz: r2
  });

  it("sums each engine's asset bytes into totalBytes", () => {
    const dir = makeFullFixture();
    const out = genEngineManifest(scanEngines(dir));
    expect(out).toContain("totalBytes: 2500,"); // baz: 2000 + 500
    expect(out).toContain("totalBytes: 1024,"); // foo: single asset
    expect(out).toContain("totalBytes: 0,"); // bar: no assets
  });
});

describe("genEngineLoaders", () => {
  it("is an empty, still-valid loader map for zero engines", () => {
    const out = genEngineLoaders([]);
    expect(out).toContain("export const ENGINE_LOADERS = {} satisfies Record<");
  });

  it("imports each engine's adapter by its own relative path", () => {
    const dir = makeFullFixture();
    const out = genEngineLoaders(scanEngines(dir));
    expect(out).toContain('bar: () => import("./bar/adapter"),');
    expect(out).toContain('baz: () => import("./baz/adapter"),');
    expect(out).toContain('foo: () => import("./foo/adapter"),');
  });
});

// ---------------------------------------------------------------------------
// generate — full pipeline
// ---------------------------------------------------------------------------

describe("generate", () => {
  it("produces the four expected files for an empty repo", () => {
    const files = generate(makeTempDir());
    expect([...files.keys()].sort()).toEqual([
      "src/lib/engines/ids.ts",
      "src/lib/engines/loaders.ts",
      "src/lib/engines/manifest.ts",
      "src/tools/index.ts",
    ]);
    expect(get(files, "src/tools/index.ts")).toContain(
      "export const TOOLS: readonly ToolDefinition[] = [];",
    );
    expect(get(files, "src/lib/engines/ids.ts")).toContain(
      "export type EngineId = never;",
    );
  });

  it("is deterministic: two runs against the same rootDir produce identical output", () => {
    const dir = makeFullFixture();
    const first = [...generate(dir).entries()];
    const second = [...generate(dir).entries()];
    expect(second).toEqual(first);
  });

  it("propagates an engine validation error", () => {
    const dir = makeTempDir();
    writeFile(
      dir,
      "src/lib/engines/foo/engine.json",
      engineJson({ id: "nope" }),
    );
    writeFile(dir, "src/lib/engines/foo/adapter.ts", "export default {};\n");
    expect(() => generate(dir)).toThrow(/must match its directory name/);
  });
});
