import { describe, expect, it } from "vitest";
import { CATALOG } from "./catalog";
import { TOOLS } from "./index";

/**
 * `catalog.ts` is generated by reading each tool file's source text (never
 * importing it — see scripts/gen-registry.ts), so it could drift from what
 * the tools actually declare if a field ever stops being a plain literal.
 * This compares every row against the real, imported registry.
 */
describe("generated catalog matches the registry", () => {
  it("has exactly one row per tool", () => {
    expect(CATALOG.map((row) => row.slug).sort()).toEqual(
      TOOLS.map((tool) => tool.slug).sort(),
    );
  });

  it("agrees with every tool's own fields", () => {
    const bySlug = new Map(CATALOG.map((row) => [row.slug, row]));
    for (const tool of TOOLS) {
      const row = bySlug.get(tool.slug);
      expect(row, tool.slug).toBeDefined();
      expect(
        {
          title: row?.title,
          category: row?.category,
          accepts: row?.accepts,
          produces: row?.produces,
          kind: row?.kind,
          arity: row?.arity,
          rank: row?.rank,
        },
        tool.slug,
      ).toEqual({
        title: tool.title,
        category: tool.category,
        accepts: tool.accepts,
        produces: tool.produces,
        kind: tool.kind ?? "job",
        arity: tool.arity ?? "one-to-one",
        rank: tool.rank,
      });
    }
  });
});
