// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.
import type { ToolDefinition } from "@/lib/registry";

export const TOOLS: readonly ToolDefinition[] = [];

export const TOOLS_BY_SLUG: ReadonlyMap<string, ToolDefinition> = new Map(
  TOOLS.map((t) => [t.slug, t]),
);
