// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.
import type { ToolDefinition } from "@/lib/registry";
import compressJpg from "@/tools/image/compress-jpg";
import compressWebp from "@/tools/image/compress-webp";
import jpgToPng from "@/tools/image/jpg-to-png";
import resizeImageJpg from "@/tools/image/resize-image-jpg";
import resizeImagePng from "@/tools/image/resize-image-png";
import resizeImageWebp from "@/tools/image/resize-image-webp";
import rotateJpg from "@/tools/image/rotate-jpg";
import rotatePng from "@/tools/image/rotate-png";
import rotateWebp from "@/tools/image/rotate-webp";

export const TOOLS: readonly ToolDefinition[] = [
  compressJpg,
  compressWebp,
  jpgToPng,
  resizeImageJpg,
  resizeImagePng,
  resizeImageWebp,
  rotateJpg,
  rotatePng,
  rotateWebp,
];

export const TOOLS_BY_SLUG: ReadonlyMap<string, ToolDefinition> = new Map(
  TOOLS.map((t) => [t.slug, t]),
);
