// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.
import type { ToolDefinition } from "@/lib/registry";
import extractAudio from "@/tools/audio/extract-audio";
import flacToMp3 from "@/tools/audio/flac-to-mp3";
import m4aToMp3 from "@/tools/audio/m4a-to-mp3";
import mp3ToM4a from "@/tools/audio/mp3-to-m4a";
import mp3ToOgg from "@/tools/audio/mp3-to-ogg";
import mp3ToWav from "@/tools/audio/mp3-to-wav";
import oggToMp3 from "@/tools/audio/ogg-to-mp3";
import wavToFlac from "@/tools/audio/wav-to-flac";
import wavToMp3 from "@/tools/audio/wav-to-mp3";
import avifToJpg from "@/tools/image/avif-to-jpg";
import avifToPng from "@/tools/image/avif-to-png";
import compressJpg from "@/tools/image/compress-jpg";
import compressWebp from "@/tools/image/compress-webp";
import cropJpg from "@/tools/image/crop-jpg";
import cropPng from "@/tools/image/crop-png";
import cropWebp from "@/tools/image/crop-webp";
import heicToJpg from "@/tools/image/heic-to-jpg";
import heicToPng from "@/tools/image/heic-to-png";
import imageToText from "@/tools/image/image-to-text";
import jpgToAvif from "@/tools/image/jpg-to-avif";
import jpgToJxl from "@/tools/image/jpg-to-jxl";
import jpgToPng from "@/tools/image/jpg-to-png";
import jpgToSvg from "@/tools/image/jpg-to-svg";
import jpgToWebp from "@/tools/image/jpg-to-webp";
import jxlToJpg from "@/tools/image/jxl-to-jpg";
import jxlToPng from "@/tools/image/jxl-to-png";
import pngToAvif from "@/tools/image/png-to-avif";
import pngToJpg from "@/tools/image/png-to-jpg";
import pngToJxl from "@/tools/image/png-to-jxl";
import pngToSvg from "@/tools/image/png-to-svg";
import pngToWebp from "@/tools/image/png-to-webp";
import psdToJpg from "@/tools/image/psd-to-jpg";
import psdToPng from "@/tools/image/psd-to-png";
import rawToJpg from "@/tools/image/raw-to-jpg";
import rawToPng from "@/tools/image/raw-to-png";
import resizeImageJpg from "@/tools/image/resize-image-jpg";
import resizeImagePng from "@/tools/image/resize-image-png";
import resizeImageWebp from "@/tools/image/resize-image-webp";
import rotateJpg from "@/tools/image/rotate-jpg";
import rotatePng from "@/tools/image/rotate-png";
import rotateWebp from "@/tools/image/rotate-webp";
import stripExif from "@/tools/image/strip-exif";
import svgToJpg from "@/tools/image/svg-to-jpg";
import svgToPng from "@/tools/image/svg-to-png";
import tiffToJpg from "@/tools/image/tiff-to-jpg";
import tiffToPng from "@/tools/image/tiff-to-png";
import webpToJpg from "@/tools/image/webp-to-jpg";
import webpToPng from "@/tools/image/webp-to-png";
import webpToSvg from "@/tools/image/webp-to-svg";
import compressPdf from "@/tools/pdf/compress-pdf";
import deletePdfPages from "@/tools/pdf/delete-pdf-pages";
import extractPdfPages from "@/tools/pdf/extract-pdf-pages";
import flattenPdf from "@/tools/pdf/flatten-pdf";
import imageToSearchablePdf from "@/tools/pdf/image-to-searchable-pdf";
import imagesToPdf from "@/tools/pdf/images-to-pdf";
import mergePdf from "@/tools/pdf/merge-pdf";
import pdfEditor from "@/tools/pdf/pdf-editor";
import pdfToJpg from "@/tools/pdf/pdf-to-jpg";
import pdfToPng from "@/tools/pdf/pdf-to-png";
import pdfToSearchablePdf from "@/tools/pdf/pdf-to-searchable-pdf";
import protectPdf from "@/tools/pdf/protect-pdf";
import reorderPdfPages from "@/tools/pdf/reorder-pdf-pages";
import rotatePdf from "@/tools/pdf/rotate-pdf";
import sanitizePdf from "@/tools/pdf/sanitize-pdf";
import splitPdf from "@/tools/pdf/split-pdf";
import unlockPdf from "@/tools/pdf/unlock-pdf";
import aviToMp4 from "@/tools/video/avi-to-mp4";
import compressVideo from "@/tools/video/compress-video";
import flvToMp4 from "@/tools/video/flv-to-mp4";
import mkvToMp4 from "@/tools/video/mkv-to-mp4";
import movToMp4 from "@/tools/video/mov-to-mp4";
import movToWebm from "@/tools/video/mov-to-webm";
import mp4ToMov from "@/tools/video/mp4-to-mov";
import mp4ToWebm from "@/tools/video/mp4-to-webm";
import muteVideo from "@/tools/video/mute-video";
import resizeVideo from "@/tools/video/resize-video";
import rotateVideo from "@/tools/video/rotate-video";
import trimVideo from "@/tools/video/trim-video";
import videoToGif from "@/tools/video/video-to-gif";
import webmToMp4 from "@/tools/video/webm-to-mp4";
import wmvToMp4 from "@/tools/video/wmv-to-mp4";

export const TOOLS: readonly ToolDefinition[] = [
  extractAudio,
  flacToMp3,
  m4aToMp3,
  mp3ToM4a,
  mp3ToOgg,
  mp3ToWav,
  oggToMp3,
  wavToFlac,
  wavToMp3,
  avifToJpg,
  avifToPng,
  compressJpg,
  compressWebp,
  cropJpg,
  cropPng,
  cropWebp,
  heicToJpg,
  heicToPng,
  imageToText,
  jpgToAvif,
  jpgToJxl,
  jpgToPng,
  jpgToSvg,
  jpgToWebp,
  jxlToJpg,
  jxlToPng,
  pngToAvif,
  pngToJpg,
  pngToJxl,
  pngToSvg,
  pngToWebp,
  psdToJpg,
  psdToPng,
  rawToJpg,
  rawToPng,
  resizeImageJpg,
  resizeImagePng,
  resizeImageWebp,
  rotateJpg,
  rotatePng,
  rotateWebp,
  stripExif,
  svgToJpg,
  svgToPng,
  tiffToJpg,
  tiffToPng,
  webpToJpg,
  webpToPng,
  webpToSvg,
  compressPdf,
  deletePdfPages,
  extractPdfPages,
  flattenPdf,
  imageToSearchablePdf,
  imagesToPdf,
  mergePdf,
  pdfEditor,
  pdfToJpg,
  pdfToPng,
  pdfToSearchablePdf,
  protectPdf,
  reorderPdfPages,
  rotatePdf,
  sanitizePdf,
  splitPdf,
  unlockPdf,
  aviToMp4,
  compressVideo,
  flvToMp4,
  mkvToMp4,
  movToMp4,
  movToWebm,
  mp4ToMov,
  mp4ToWebm,
  muteVideo,
  resizeVideo,
  rotateVideo,
  trimVideo,
  videoToGif,
  webmToMp4,
  wmvToMp4,
];

export const TOOLS_BY_SLUG: ReadonlyMap<string, ToolDefinition> = new Map(
  TOOLS.map((t) => [t.slug, t]),
);
