// GENERATED by scripts/gen-registry.ts — do not edit. Run `pnpm gen`.
import type { ToolDefinition } from "@/lib/registry";

export const TOOL_LOADERS = {
  "heic-to-jpg": () => import("./image/heic-to-jpg"),
  "heic-to-png": () => import("./image/heic-to-png"),
  "jpg-to-png": () => import("./image/jpg-to-png"),
  "psd-to-jpg": () => import("./image/psd-to-jpg"),
  "psd-to-png": () => import("./image/psd-to-png"),
  "svg-to-jpg": () => import("./image/svg-to-jpg"),
  "svg-to-png": () => import("./image/svg-to-png"),
  "tiff-to-jpg": () => import("./image/tiff-to-jpg"),
  "tiff-to-png": () => import("./image/tiff-to-png"),
} satisfies Record<string, () => Promise<{ default: ToolDefinition }>>;
